spring:
  application:
    name: ruyuan-eshop-order
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ruyuan_eshop_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      min-idle: 1
      initial-size: 1
      max-active: 5
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
      filters: stat
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000

server:
  port: 8005

dubbo:
  scan:
    base-packages: com.ruyuan.eshop.order.api
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28085
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
  cloud:
    subscribed-services: ruyuan-eshop-order,ruyuan-eshop-product,ruyuan-eshop-market,ruyuan-eshop-inventory,ruyuan-eshop-pay,ruyuan-eshop-customer,ruyuan-eshop-risk,ruyuan-eshop-address,ruyuan-eshop-fulfill,ruyuan-eshop-wms,ruyuan-eshop-tms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


rocketmq:
  name-server: 101.132.128.144:9876

#seata配置
seata:
  enable-auto-data-source-proxy: false # 如果引入的是seata-spring-boot-starter 请关闭自动代理，需要关闭自动代理
  application-id: seata-server # Seata应用的名称
  tx-service-group: default_tx_group # 事务组
  service:
    vgroup-mapping:
      default_tx_group: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos服务地址
      namespace: seata # Seata的NameSpace ID
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos # 基于Nacos实现分布式事务管理
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos服务地址
      namespace: seata # Seata的NameSpace ID
      group: SEATA_GROUP
      username: nacos
      password: nacos
      cluster: default
      application: seata-server

xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: ruyuan-order-service